What - refien the param of scanf
@Description/root cause - Why
build error on 64bit ubuntu 12.04
kpfs_node.c:175:3: error: format '%llu' expects argument of type 'long long
unsigned int *', but argument 3 has type 'off_t *' [-Werror=format]

@Resolution - How
1. change range parameter from
"%llu"
to
CURL_FORMAT_OFF_T
otherwise, it will show compile error on some systems.
this is similar with following issue:
http://code.google.com/p/kpfs/issues/detail?id=2

@Reviewer
None

@Tickets
NONE